CREATE TABLE IF NOT EXISTS bot_user_sessions (
  telegram_user_id BIGINT PRIMARY KEY,
  action VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
